### ISSUE TITLE
Add yarn support for @risingstack/trace package

### ISSUE THREAD

**Issue by igorify** [RisingStack/trace-nodejs#144]
Hi. 
I can`t use quick yarn installing having @risingstack/trace in dependencies.

`"dependencies": {
    "@risingstack/trace": "^3.5.2"
 }`

Yarn show this error:

`
[3/4] 🔗  Linking dependencies...

error Couldn't find a package.json file in "app/node_modules/@risingstack/event-loop-stats/node_modules/node-pre-gyp"
`

Could you provide yarn support for @risingstack/trace package?

**Comment by oliviertassinari** [comment]
Same issue with `"@risingstack/trace": "^3.12.2",`.

**Comment by gergelyke** [comment]
Seems like an issue with yarn - we are looking into it, as well as asked help from the team behind yarn: https://github.com/yarnpkg/yarn/issues/3736

**Comment by derN3rd** [comment]
Are you still on it?

Can't install trace via yarn/npm. So I can't use trace in any way because of this...

yarn output:
```
berlin:~/Projects/App-node: yarn add @risingstack/trace
yarn add v0.27.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/@risingstack%2ftrace: User not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/derN3rd/Projects/App-node/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

npm output:
```
berlin:~/Projects/App-node: npm install --save @risingstack/trace
npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "@risingstack/trace"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0

npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/derN3rd/.npm/_logs/2017-07-27T11_26_20_757Z-debug.log
```

**Comment by levsthings** [comment]
Also unable to install via yarn.

yarn output:
```
yarn add v0.24.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error Couldn't find a package.json file in "F:\\os-package\\mono\\node_modules\\@risingstack\\event-loop-stats\\node_modules\\node-pre-gyp"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
``

**Comment by gergelyke** [comment]
fixed in the latest version

**Comment by derN3rd** [comment]
It's still not fixed for me. Still getting the same error with yarn. Same as on [my last comment
](https://github.com/RisingStack/trace-nodejs/issues/144#issuecomment-318338522)
